[package]
name = "magehand-be-yul"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magehand-core = { version = "0.1", path = "../core" }
